config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, skip: [:registrations], controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords'
  }
  namespace :admin do
    get 'top/index'
    get 'top/about'
    get 'top/show'
    resources :shops
    resources :shop_details
    resources :menus
    get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
    get 'shop_details/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  end

  root 'top#index'

  mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations, :omniauth_callbacks]
  get 'api-docs', to: 'api_docs#index'
  get 'pref_shops/search'
  get 'pref_shops/:prefecture_id/shops/search' => 'shops#search_by_prefecture', as: 'shops_search_by_prefecture'
  get 'shops/search' => 'shops#search_by_keyword', as: 'shops_search_by_keyword'
  get 'shops/:id' => 'shops#shop_detail', as: 'shop_detail'
  get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
  resources :reviews, only: [:create, :update, :destroy]
  get 'menus/:id/reviews' => 'reviews#index'

  # devise_for :users, controllers: {
  #   sessions:      'users/sessions',
  #   passwords:     'users/passwords',
  #   registrations: 'users/registrations'
  # }

  # get 'shops/:id/menu' => 'shops#shop_menu', as: 'shop_menu'
  # resources :menus
  # get 'shop_detail/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  # resources :shop_details
  # resources :user_profiles
  # resources :users do
  #   member do
  #    get :following, :followers, :eaten_menus, :desired_menus, :likes
  #   end
  # end
  # resources :relationships, only: [:create, :destroy]
  # resources :eaten_menus, only: [:create, :destroy]
  # resources :desired_menus, only: [:create, :destroy]
  # resources :likes, only: [:create, :destroy]
  # get 'comments/:review_id/new' => 'comments#new', as: 'comments_new'
  # resources :comments
  # resources :cheerings, only: [:create, :destroy]

end

app/models/shop.rb
class Shop < ApplicationRecord
  enum tkg_flg: { not_tkg:0, tkg:1}
  has_many :menus
  has_many :cheerings, class_name: "Cheering",
                      foreign_key: "shop_id",
                      dependent: :destroy
  has_one :shop_detail
  belongs_to :prefecture
  mount_uploader :prof_picture, ImageUploader
  validates :name, presence: true;
  validates :address, presence: true;
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::ApplicationController

  # def index
  #   @shops = Shop.all
  # end

  def index
    @q = Shop.ransack(search_params)
    @shops = @q.result(distinct: true)
  end

  def new
    @shop = Shop.new()
    @prefectures = Prefecture.all
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save
    @shop_detail = ShopDetail.new(
      shop_id: @shop.id
    )
    @shop_detail.save
    redirect_to admin_shop_path(@shop.id)
  end

  def show
    @shop = Shop.find_by(id: params[:id])
    @shop_detail = ShopDetail.find_by(shop_id: params[:id])
  end

  def edit
    @shop = Shop.find_by(id: params[:id])
  end

  def update
    @shop = Shop.find_by(id: params[:id])
    @shop.update(shop_params)
    redirect_to admin_shop_path
  end

  def destroy
    @shop.find_by(id: params[:id])
    @shop.destroy
    redirect_to admin_shop_path
  end

  def shop_menu # shopに紐づくmenuの一覧表示
    @shop = Shop.find_by(id: params[:id])
    @shop_menus = @shop.menus # 関連付けを利用して店舗に紐づくメニューを取得
  end

  private

    def shop_params
      params.require(:shop).permit(:name, :kana, :address, :tel, :prof_picture, :tkg_flg, :prefecture_id)
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def search_by_prefecture
    @shops = Shop.where('tkg_flg = 1 AND prefecture_id = ?', params[:prefecture_id])
    render json: @shops, only:[:id, :name, :address, :tel, :prof_picture]
  end

  def search_by_keyword
    keywords = params[:q].gsub(/¥s|　/, ' ').split(" ") unless params[:q].blank?
    if keywords.present?
      keywords.each_with_index do |keyword, i|
        if i == 0
          @shops = Shop.where('name LIKE ?', "%#{keyword}%")
          next
        end
        @shops = @shops.where('name LIKE ?', "%#{keyword}%")
      end
      @shops = @shops.where('tkg_flg = 1')
    end
    render json: @shops, only:[:id, :name, :address, :tel, :prof_picture]
  end

  def shop_detail
    @shop_detail = ShopDetail.find_by(shop_id: params[:id])
    render json: @shop_detail, only:[:operating_hours, :holiday, :payment]
  end

  def shop_menu
    @menus = Menu.where(shop_id: params[:id])
    render json: @menus, only:[:id, :name, :price, :type, :prof_picture]
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_cheering_register.html.erb
<%= form_tag(cheerings_path) do |f| %>
  <div><%= hidden_field_tag :shop_id, @shop.id %></div>
  <%= submit_tag "応援する", id: "cheering_register_btn" %>
<% end %>

app/views/shops/_cheering_register_form.html.erb
<% if current_user %>
  <div class="register_form">
  <% if current_user.cheerings.find_by(shop_id: params[:id]) %>
    <%= render 'cheering_unregister' %>
  <% else %>
    <%= render 'cheering_register' %>
  <% end %>
  </div>
<% end %>

app/views/shops/_cheering_unregister.html.erb
<%= form_tag(cheering_path(@shop), method: :delete ) do |f| %>
  <div><%= hidden_field_tag :shop_id, @shop.id %></div>
  <%= submit_tag "応援をやめる", id: "cheering_register_btn" %>
<% end %>

app/views/shops/edit.html.erb
<nav class="sp-header">
  <div class="container">
    <%= link_to "Menumeal", root_path, class: "sp-header-logo" %>
  </div>
</nav>

<section class="sp-form-wrapper">
  <h1 class="sp-form-title">店舗基本情報を修正</h1>
<%= form_for(@shop, url: shop_path(@shop) ) do |f| %>
  <!-- <%= f.label :name, '店舗名' %><br/> -->
  <h3 class="sp-form-label">店舗名</h3>
  <%= f.text_field :name, size: 25, class: "sp-form-text" %><br/>

  <!-- <%= f.label :kana, 'よみがな(店舗名)' %><br/> -->
  <h3 class="sp-form-label">よみがな(店舗名)</h3>
  <%= f.text_field :kana, size: 25, class: "sp-form-text" %><br/>

  <!-- <%= f.label :address,'住所' %><br/> -->
  <h3 class="sp-form-label">住所</h3>
  <%= f.text_field :address, size: 25, class: "sp-form-text" %><br/>

  <!-- <%= f.label :tel, '電話番号' %><br/> -->
  <h3 class="sp-form-label">電話番号</h3>
  <%= f.text_field :tel, size: 12, class: "sp-form-text" %><br/>

  <h3 class="sp-form-label">画像</h3>
  <%= f.label :prof_picture, '　画像追加', {class: "input_file fa fa-camera"} %><br/>
  <%= f.file_field :prof_picture %><br/>

  <%= f.submit '編集を登録', class: "sp-form-submit" %>
<% end %>
</section>

app/views/shops/new.html.erb
<nav class="sp-header">
  <div class="container">
    <%= link_to "Menumeal", root_path, class: "sp-header-logo" %>
  </div>
</nav>

<section class="sp-form-wrapper">
<h1 class="sp-form-title">店舗登録</h1>
<%= form_for(@shop, url: shops_path) do |f| %>
  <!-- <%= f.label :name, '店舗名', class: "sp-form-label" %><br/> -->
  <h3 class="sp-form-label">店舗名</h3>
  <%= f.text_field :name, size: 25, placeholder: "例) menumealカフェ", class: "sp-form-text" %><br/>

  <!-- <%= f.label :kana, 'よみがな(店舗名)', class: "sp-form-label" %><br/> -->
  <h3 class="sp-form-label">よみがな(店舗名)</h3>
  <%= f.text_field :kana, size: 25, placeholder: "例) めにゅみーるかふぇ", class: "sp-form-text" %><br/>

  <!-- <%= f.label :address,'住所', class: "sp-form-label" %><br/> -->
  <h3 class="sp-form-label">住所</h3>
  <%= f.text_field :address, size: 25, placeholder: "例) 東京都 ◯◯ ◯◯", class: "sp-form-text" %><br/>

  <!-- <%= f.label :tel, '電話番号', class: "sp-form-label" %><br/> -->
  <h3 class="sp-form-label">電話番号</h3>
  <%= f.text_field :tel, size: 12, placeholder: "例) 0000-00-0000", class: "sp-form-text" %><br/>

  <h3 class="sp-form-label">画像</h3>
  <%= f.label :prof_picture, '　画像追加', {class: "input_file fa fa-camera"} %><br/>
  <%= f.file_field :prof_picture %><br/>

  <%= f.submit '店舗を登録', class: "sp-form-submit" %>
<% end %>
<section>

app/views/shops/shop_menu.html.erb
<div class="shop_menus_container">
<nav class="sp-header">
  <div class="container">
    <%= link_to "Menumeal", root_path, class: "sp-header-logo" %>
  </div>
</nav>

<section class="shop-top-wrapper">
  <%= image_tag(@shop.prof_picture, class: "shop-image") %>
  <div class="container">
    <h1 class="shop-name"><%= @shop.name %></h1>
    <% if @shop.kana.present? %>
      <span class="shop-kana">(<%= @shop.kana %>)</span>
    <% end %>
  </div>
</section>
<nav class="shop-nav-wrapper">
  <%= link_to "基本情報", shop_path(@shop.id), class:"shop-nav-item" %>
  <%= link_to "メニュー", shop_menu_path(@shop.id), class:"shop-nav-item" %>
</nav>

<section class="shop-menus-wrapper">
  <nav class="shop-menus-header">
    <div class="container">
      <%= link_to "＋", new_menu_path, class: "shop-menus-header-item" %>
    </div>
  </nav>
  <div class="container">
    <ul>
      <% @shop_menus.each do |menu| %>
        <%= link_to(menu_path(menu), class: "menu-container-li") do %>
          <% if menu.reviews.present? %>
            <%= image_tag menu.reviews.last.picture, size: 40, class: "menu-pict" %>
          <% else %>
            <%= image_tag "/user_picts/noimage.png", size: 40, class: "menu-pict" %>
          <% end %>
          <span class="menu-name"><%= menu.name %></span>
          <span class="menu-price"><%= menu.price %>円</span>
        <% end %>
      <% end %>
    </ul>
  </div>

</section>

app/views/shops/show.html.erb
<!-- 店舗トップページ -->
<nav class="sp-header">
  <div class="container">
    <%= link_to "Menumeal", root_path, class: "sp-header-logo" %>
  </div>
</nav>

<section class="shop-top-wrapper">
<%= image_tag(@shop.prof_picture, class: "shop-image") %>
  <div class="container">
    <h1 class="shop-name"><%= @shop.name %></h1>
    <% if @shop.kana.present? %>
      <span class="shop-kana">(<%= @shop.kana %>)</span>
    <% end %>
    <%= render 'cheering_register_form'%>
  </div>
</section>
<nav class="shop-nav-wrapper">
  <%= link_to "基本情報", shop_path(@shop.id), class:"shop-nav-item" %>
  <%= link_to "メニュー", shop_menu_path(@shop.id), class:"shop-nav-item" %>
</nav>
<section class="shop-info-wrapper">
    <div class="shop-base-info-wrapper">
      <div class="container">
        <h2 class="section-title">基本情報</h2>
        <%= link_to "修正", edit_shop_path(@shop), class: "edit-form" %>
      </div>
      <table class="shop-info-table">
        <tr>
          <th>電話番号</th>
          <td><%= @shop.tel %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @shop.address %></td>
        </tr>
      </table>
    </div>
    <div class="shop-detail-info-wrapper">
      <div class="container">
      <h2 class="section-title">詳細情報</h2>
      <%= link_to "修正", edit_shop_detail_path(@shop), class: "edit-form" %>
      </div>
      <table class="shop-info-table">
        <tr>
          <th>営業時間</th>
          <td><%= simple_format(@shop_detail.operating_hours) %></td>
        </tr>
        <tr>
          <th>定休日</th>
          <td><%= @shop_detail.holiday %></td>
        </tr>
        <tr>
          <th>アクセス</th>
          <td><%= @shop_detail.access %></td>
        </tr>
        <tr>
          <th>予算</th>
          <td><%= @shop_detail.budget %></td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @shop_detail.payment %></td>
        </tr>
        <tr>
          <th>席数</th>
          <td><%= @shop_detail.seats %></td>
        </tr>
        <tr>
          <th>個室</th>
          <td><%= @shop_detail.private_room %></td>
        </tr>
        <tr>
          <th>カウンター席</th>
          <td><%= @shop_detail.bar %></td>
        </tr>
        <tr>
          <th>喫煙</th>
          <td><%= @shop_detail.smoking %></td>
        </tr>
        <tr>
          <th>駐車場</th>
          <td><%= @shop_detail.parking %></td>
        </tr>
      </table>
    </div>
</section>