config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, skip: [:registrations], controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords'
  }
  namespace :admin do
    get 'top/index'
    get 'top/about'
    get 'top/show'
    resources :shops
    resources :shop_details
    resources :menus
    get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
    get 'shop_details/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  end

  root 'top#index'

  mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations, :omniauth_callbacks]
  get 'api-docs', to: 'api_docs#index'
  get 'pref_shops/search'
  get 'pref_shops/:prefecture_id/shops/search' => 'shops#search_by_prefecture', as: 'shops_search_by_prefecture'
  get 'shops/search' => 'shops#search_by_keyword', as: 'shops_search_by_keyword'
  get 'shops/:id' => 'shops#shop_detail', as: 'shop_detail'
  get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
  resources :reviews, only: [:create, :update, :destroy]
  get 'menus/:id/reviews' => 'reviews#index'

  # devise_for :users, controllers: {
  #   sessions:      'users/sessions',
  #   passwords:     'users/passwords',
  #   registrations: 'users/registrations'
  # }

  # get 'shops/:id/menu' => 'shops#shop_menu', as: 'shop_menu'
  # resources :menus
  # get 'shop_detail/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  # resources :shop_details
  # resources :user_profiles
  # resources :users do
  #   member do
  #    get :following, :followers, :eaten_menus, :desired_menus, :likes
  #   end
  # end
  # resources :relationships, only: [:create, :destroy]
  # resources :eaten_menus, only: [:create, :destroy]
  # resources :desired_menus, only: [:create, :destroy]
  # resources :likes, only: [:create, :destroy]
  # get 'comments/:review_id/new' => 'comments#new', as: 'comments_new'
  # resources :comments
  # resources :cheerings, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include DeviseTokenAuth::Concerns::User
  has_one :user_profile, dependent: :destroy
  has_many :reviews
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :menus
  has_many :eaten_menus, class_name: "EatenMenu",
                               foreign_key: "user_id",
                               dependent: :destroy
  has_many :desired_menus, class_name: "DesiredMenu",
                                 foreign_key: "user_id",
                                 dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cheerings, class_name: "Cheering",
                      foreign_key: "user_id",
                      dependent: :destroy
  after_create :init_user_profile
  mount_uploader :prof_picture, ImageUploader

  validates :name, presence: true,
                    uniqueness: true
  validates :email, uniqueness: true

  # 空のユーザープロフィールを作成する
  def init_user_profile
    self.create_user_profile!
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 現在のユーザーが食べたメニューに登録していたらtrueを返す
  def registering_eaten_menu?(menu)
    eaten_menus.include?(menu)
  end

  # 現在のユーザーが食べたいメニューに登録していたらtrueを返す
  def registering_desired_menu?(menu)
    desired_menus.include?(menu)
  end

  # 現在のユーザーがいいねしていたらtrueを返す
  def like?(review)
    likes.include?(review)
  end

  # 現在のユーザーが応援していたらtrueを返す
  def registering_cheering?(shop)
    cheerings.include?(shop)
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by(id: params[:id])
        @user_profile = @user.user_profile
        @reviews = @user.reviews.order(created_at: :desc)
    end

    def following
        @title = "フォロー中"
        @user = User.find(params[:id])
        @users = @user.following
        render 'show_follow'
    end

    def followers
        @title = "フォロワー"
        @user = User.find(params[:id])
        @users = @user.followers
        render 'show_follow'
    end

    def eaten
        @title = "食べたメニュー登録中"
        @user = User.find(params[:id]).registering_eaten_menu
        render 'show_registering_eaten_menu'
    end

    def desired
        @title = "食べたいメニュー登録中"
        @user = User.find(params[:id]).registering_desired_menu
        render 'show_registering_desired_menu'
    end

    def eaten_menus
      @user = User.find_by(id: params[:id])
      @user_profile = @user.user_profile
      @eaten_menus = @user.eaten_menus.order(created_at: :desc)
    end

    def desired_menus
      @user = User.find_by(id: params[:id])
      @user_profile = @user.user_profile
      @desired_menus = @user.desired_menus.order(created_at: :desc)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "f-btn follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %><!--ログイン中のユーザーと表示するユーザーが異なればボタンを表示する -->
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "f-btn" %>
<% end %>

app/views/users/desired_menus.html.erb
<section class="user-top-wrapper">
    <div class="container">
      <div class="user-top-top">
        <% if @user ==  current_user %>
          <% if @user.prof_picture? %>
           <%= link_to image_tag(@user.prof_picture, class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% else %>
           <%= link_to image_tag('/user_picts/default.png', class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% end %>
        <% else %>
          <% if @user.prof_picture? %>
          <div class="user-top-left">
           <%= image_tag(@user.prof_picture, class: "user-icon") %>
          </div>
          <% else %>
          <div class="user-top-left">
           <%= image_tag('/user_picts/default.png', class: "user-icon") %>
          </div>
          <% end %>
        <% end %>

        <div class="user-top-right">
          <div class="user-top-right-top">
            <!-- ユーザーネーム、設定 -->
            <span class="user-name"><%= @user.name %></span>
            <% if @user == current_user%>
              <%= link_to "◯", edit_user_registration_path, class: "settings-icon" %>
            <% end %>
          </div>
          <div class="user-top-right-bottom">
            <!-- 投稿、フォロー、フォロワー -->
            <div class="user-relation-info">
              <%= link_to @user.reviews.count, user_path(@user), class: "count" %>
              <span class="type">投稿</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.followers.count, followers_user_path(@user), class: "count" %>
              <span class="type">フォロワー</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.following.count, following_user_path(@user), class: "count" %>
              <span class="type">フォロー中</span>
            </div>
          </div>
        </div>

      </div>

      <div class="user-top-bottom">
        <!-- ユーザープロフィール文 -->
        <span class="user-profile"><%= @user_profile.profile %></span>
      </div>

    </div>
</section>

<nav class="user-nav-wrapper">
  <div class="container">
    <%= link_to "投稿", user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べた", eaten_menus_user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べたい", desired_menus_user_path(params[:id]), class: "user-nav-item" %>
  </div>
</nav>

<section class="user-bottom-wrapper">
  <div class="reviews-container">
    <% @desired_menus.each do |desired_menu| %>
      <%= link_to image_tag(desired_menu.menu.reviews.last.picture, class: "user-review-image"), review_path(desired_menu.menu_id), class: "user-review-container" %>
    <% end %>
  </div>
</section>

app/views/users/eaten_menus.html.erb
<section class="user-top-wrapper">
    <div class="container">
      <div class="user-top-top">
        <% if @user ==  current_user %>
          <% if @user.prof_picture? %>
           <%= link_to image_tag(@user.prof_picture, class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% else %>
           <%= link_to image_tag('/user_picts/default.png', class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% end %>
        <% else %>
          <% if @user.prof_picture? %>
          <div class="user-top-left">
           <%= image_tag(@user.prof_picture, class: "user-icon") %>
          </div>
          <% else %>
          <div class="user-top-left">
           <%= image_tag('/user_picts/default.png', class: "user-icon") %>
          </div>
          <% end %>
        <% end %>

        <div class="user-top-right">
          <div class="user-top-right-top">
            <!-- ユーザーネーム、設定 -->
            <span class="user-name"><%= @user.name %></span>
            <% if @user == current_user%>
              <%= link_to "◯", edit_user_registration_path, class: "settings-icon" %>
            <% end %>
          </div>
          <div class="user-top-right-bottom">
            <!-- 投稿、フォロー、フォロワー -->
            <div class="user-relation-info">
              <%= link_to @user.reviews.count, user_path(@user), class: "count" %>
              <span class="type">投稿</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.followers.count, followers_user_path(@user), class: "count" %>
              <span class="type">フォロワー</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.following.count, following_user_path(@user), class: "count" %>
              <span class="type">フォロー中</span>
            </div>
          </div>
        </div>

      </div>

      <div class="user-top-bottom">
        <!-- ユーザープロフィール文 -->
        <span class="user-profile"><%= @user_profile.profile %></span>
      </div>

    </div>
</section>

<nav class="user-nav-wrapper">
  <div class="container">
    <%= link_to "投稿", user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べた", eaten_menus_user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べたい", desired_menus_user_path(params[:id]), class: "user-nav-item" %>
  </div>
</nav>

<section class="user-bottom-wrapper">
  <div class="reviews-container">
    <% @eaten_menus.each do |eaten_menu| %>
      <%= link_to image_tag(eaten_menu.menu.reviews.last.picture, class: "user-review-image"), review_path(eaten_menu.menu_id), class: "user-review-container" %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="user-top-wrapper">
    <div class="container">
      <div class="user-top-top">
        <% if @user ==  current_user %>
          <% if @user.prof_picture? %>
           <%= link_to image_tag(@user.prof_picture, class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% else %>
           <%= link_to image_tag('/user_picts/default.png', class: "user-icon"), edit_user_registration_path, class: "user-top-left" %>
          <% end %>
        <% else %>
          <% if @user.prof_picture? %>
          <div class="user-top-left">
           <%= image_tag(@user.prof_picture, class: "user-icon") %>
          </div>
          <% else %>
          <div class="user-top-left">
           <%= image_tag('/user_picts/default.png', class: "user-icon") %>
          </div>
          <% end %>
        <% end %>

        <div class="user-top-right">
          <div class="user-top-right-top">
            <!-- ユーザーネーム、設定 -->
            <span class="user-name"><%= @user.name %></span>
            <% if @user == current_user%>
              <%= link_to "◯", edit_user_registration_path, class: "settings-icon" %>
            <% else %>
              <%= render 'follow_form' %>
            <% end %>
          </div>
          <div class="user-top-right-bottom">
            <!-- 投稿、フォロー、フォロワー -->
            <div class="user-relation-info">
              <%= link_to @user.reviews.count, user_path(@user), class: "count" %>
              <span class="type">投稿</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.followers.count, followers_user_path(@user), class: "count" %>
              <span class="type">フォロワー</span>
            </div>
            <div class="user-relation-info">
              <%= link_to @user.following.count, following_user_path(@user), class: "count" %>
              <span class="type">フォロー中</span>
            </div>
          </div>
        </div>

      </div>

      <div class="user-top-bottom">
        <!-- ユーザープロフィール文 -->
        <span class="user-profile"><%= @user_profile.profile %></span>
      </div>

    </div>
</section>

<nav class="user-nav-wrapper">
  <div class="container">
    <%= link_to "投稿", user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べた", eaten_menus_user_path(params[:id]), class: "user-nav-item" %>
    <%= link_to "食べたい", desired_menus_user_path(params[:id]), class: "user-nav-item" %>
  </div>
</nav>

<section class="user-bottom-wrapper">
  <div class="reviews-container">
    <% @reviews.each do |review| %>
      <%= link_to image_tag(review.picture, class: "user-review-image"), review_path(review.id), class: "user-review-container" %>
    <% end %>
  </div>
</section>

app/views/users/show_follow.html.erb
<div class="follow-container">
  <div class="container">
  <h1 class="follow_title"><%= @title %></h1>
  <% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <div class="follow_user_container">
        <div class="f_u_c_left">
          <%= link_to image_tag(user.prof_picture,size: 50), user_path(user), class: "user_icon" %>
          <%= link_to user.name, user_path(user), class: "f_user_name" %>
        </div>
        <% if current_user != user%>
          <div id="follow_form">
          <% if current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                         html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー中", class: "f_btn", id: "unfollow" %>
            <% end %>
          <% else %>
            <%= form_for(current_user.active_relationships.build) do |f| %>
              <div><%= hidden_field_tag :followed_id, user.id %></div>
              <%= f.submit "フォローする", class: "f_btn flollow", id: "follow" %>
            <% end %>
          <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>