config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, skip: [:registrations], controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords'
  }
  namespace :admin do
    get 'top/index'
    get 'top/about'
    get 'top/show'
    resources :shops
    resources :shop_details
    resources :menus
    get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
    get 'shop_details/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  end

  root 'top#index'

  mount_devise_token_auth_for 'User', at: 'auth', skip: [:token_validations, :omniauth_callbacks]
  get 'api-docs', to: 'api_docs#index'
  get 'pref_shops/search'
  get 'pref_shops/:prefecture_id/shops/search' => 'shops#search_by_prefecture', as: 'shops_search_by_prefecture'
  get 'shops/search' => 'shops#search_by_keyword', as: 'shops_search_by_keyword'
  get 'shops/:id' => 'shops#shop_detail', as: 'shop_detail'
  get 'shops/:id/menus' => 'shops#shop_menu', as: 'shop_menu'
  resources :reviews, only: [:create, :update, :destroy]
  get 'menus/:id/reviews' => 'reviews#index'

  # devise_for :users, controllers: {
  #   sessions:      'users/sessions',
  #   passwords:     'users/passwords',
  #   registrations: 'users/registrations'
  # }

  # get 'shops/:id/menu' => 'shops#shop_menu', as: 'shop_menu'
  # resources :menus
  # get 'shop_detail/:id/new' => 'shop_details#new', as: 'shop_detail_new'
  # resources :shop_details
  # resources :user_profiles
  # resources :users do
  #   member do
  #    get :following, :followers, :eaten_menus, :desired_menus, :likes
  #   end
  # end
  # resources :relationships, only: [:create, :destroy]
  # resources :eaten_menus, only: [:create, :destroy]
  # resources :desired_menus, only: [:create, :destroy]
  # resources :likes, only: [:create, :destroy]
  # get 'comments/:review_id/new' => 'comments#new', as: 'comments_new'
  # resources :comments
  # resources :cheerings, only: [:create, :destroy]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cheering.rb
class Cheering < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  validates :user, presence: true
  validates :shop, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :user_id, presence: true
  validates :review_id, presence: true
  validates :content, presence: true,
                      length: { maximum: 400 }
end

app/models/desired_menu.rb
class DesiredMenu < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :user, presence: true
  validates :menu, presence: true
end

app/models/eaten_menu.rb
class EatenMenu < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :user, presence: true
  validates :menu, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :user, presence: true
  validates :review, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  enum status: { available:0, sold_out:1, end_of_sale:2 }
  enum menu_type: { food:0, drink:1, course:2, others:9 }
  belongs_to :shop
  has_many :reviews
  has_many :users
  has_many :eaten_menus, class_name: "EatenMenu",
                        foreign_key: "menu_id",
                        dependent: :destroy
  has_many :desired_menus, class_name: "DesiredMenu",
                          foreign_key: "menu_id",
                          dependent: :destroy
  validates :shop_id, presence: true
  validates :name, presence: true,
                    length: { maximum: 90 }
  validates :menu_type, presence: true
  mount_uploader :prof_picture, ImageUploader
end

app/models/pref_shop.rb
class PrefShop
  include ActiveModel::Model

  attr_accessor :pref_id, :pref_name, :shop_count
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  self.primary_key = "prefecture_id"
  has_many :shops
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :picture, ImageUploader
  validates :user_id, presence: true
  validates :menu_id, presence: true
  validates :content, length: { maximum: 800 }

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  class << self
    def search_by_menu(menu_id)
      left_outer_joins(:user)
        .select('reviews.id as review_id, users.name as user_name, reviews.content, reviews.updated_at')
        .where(menu_id: menu_id)
        .order(id: :desc)
    end
  end
end

app/models/review_user.rb
class ReviewUser
  include ActiveModel::Model

  attr_accessor :review_id, :user_name, :content, :updated_at
end

app/models/shop.rb
class Shop < ApplicationRecord
  enum tkg_flg: { not_tkg:0, tkg:1}
  has_many :menus
  has_many :cheerings, class_name: "Cheering",
                      foreign_key: "shop_id",
                      dependent: :destroy
  has_one :shop_detail
  belongs_to :prefecture
  mount_uploader :prof_picture, ImageUploader
  validates :name, presence: true;
  validates :address, presence: true;
end

app/models/shop_detail.rb
class ShopDetail < ApplicationRecord
  belongs_to :shop
  validates :shop_id, presence: true
  validates :access, length: { maximum: 400 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include DeviseTokenAuth::Concerns::User
  has_one :user_profile, dependent: :destroy
  has_many :reviews
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :menus
  has_many :eaten_menus, class_name: "EatenMenu",
                               foreign_key: "user_id",
                               dependent: :destroy
  has_many :desired_menus, class_name: "DesiredMenu",
                                 foreign_key: "user_id",
                                 dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cheerings, class_name: "Cheering",
                      foreign_key: "user_id",
                      dependent: :destroy
  after_create :init_user_profile
  mount_uploader :prof_picture, ImageUploader

  validates :name, presence: true,
                    uniqueness: true
  validates :email, uniqueness: true

  # 空のユーザープロフィールを作成する
  def init_user_profile
    self.create_user_profile!
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 現在のユーザーが食べたメニューに登録していたらtrueを返す
  def registering_eaten_menu?(menu)
    eaten_menus.include?(menu)
  end

  # 現在のユーザーが食べたいメニューに登録していたらtrueを返す
  def registering_desired_menu?(menu)
    desired_menus.include?(menu)
  end

  # 現在のユーザーがいいねしていたらtrueを返す
  def like?(review)
    likes.include?(review)
  end

  # 現在のユーザーが応援していたらtrueを返す
  def registering_cheering?(shop)
    cheerings.include?(shop)
  end
  
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    validates :profile, length: { maximum: 400 } 
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Menumeal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
  <header class="global-header">
      <div class="container">
        <%= link_to "Menumeal", admin_top_index_path, class: "logo" %>
        <nav class="header-nav-container">
          <ul>
            <% if admin_user_signed_in? %>
              <%= link_to "使い方", admin_top_about_path, class: "header-nav-item" %>
              <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "header-nav-item" %>
            <% else %>
              <%= link_to "使い方", admin_top_about_path, class: "header-nav-item" %>
              <%= link_to 'ログイン', new_admin_user_session_path, class: "header-nav-item" %>
            <% end %>
          </ul>
        </nav>
  </header>

  <main class="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </main>
  <% if admin_user_signed_in? %>
    <nav class="sp-nav-wrapper">
      <ul class="sp-nav-container">
        <li class="sp-nav-item">
            <div class="sp-nav-icon"></div>
            <span class="sp-nav-text">ホーム</span>
          </a>
        </li>
      </ul>
    </nav>
  <% end %>
  <footer class="footer wrapper">
    <div class="container">
      <ul>
        <li><%= link_to "Menumeal", root_path, class: "footer-item" %></li>
        <li><%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "footer-item" %></li>
        <li><%= link_to "運営会社", "#", class: "footer-item" %></li>
        <li><%= link_to "利用規約", "#", class: "footer-item" %></li>
        <li><%= link_to "プライバシーポリシー", "#", class: "footer-item" %></li>
        <li><%= link_to "取材申し込み", "#", class: "footer-item" %></li>
      </ul>
      <span class="copyright">© Menumeal, Inc. All Right Reserved.</span>
    </div>
  </footer>
  </body>
</html>